version: "3.7"

services:
  crypto-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/
      - ./nodemon.json:/home/nodemon.json
    container_name: crypto-backend
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
